version: '3.9'

services:
  recorder:
    build: .
    # restart: always
    env_file:
      - .env
    volumes:
      - ${MOUNT_POINT}:/cmd/twitch-recorder

  filebrowser:
    image: filebrowser/filebrowser
    # restart: always
    env_file:
      - .env
    volumes:
      - ${MOUNT_POINT}:/cmd
      - ./filebrowser.db:/database.db
    ports: 
      - "65434:80"
    # user: "${UID}:${GID}"
    
# volumes:
