version: '3.9'

services:
  recorder:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.TSR
    # restart: always
    env_file:
      - .env
    volumes:
      - recordings:/twitch-recordings

  filebrowser:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile.FBR
      args:
        FILEBROWSER_USERNAME: $FILEBROWSER_USERNAME
        FILEBROWSER_PASSWORD: $FILEBROWSER_PASSWORD
    # restart: always
    volumes:
      - recordings:/twitch-recordings
    ports: 
      - "65434:80"
volumes:
  recordings: