FROM python:3.10.12-alpine3.18

RUN apk add --no-cache --virtual build-deps \
      gcc \
      libc-dev && \
    apk add --no-cache \
      ffmpeg \
      dumb-init && \
    pip install --no-cache-dir \
      streamlink \
      requests && \
    apk del build-deps

WORKDIR /app
COPY twitch-stream-recorder/twitch-recorder.py .
COPY configs/config.py .

CMD python3 /app/twitch-recorder.py -q ${QUALITY}